project:
  title: "ADSL GIScience and Geodatabases"
  output-dir: _slides
  

bibliography: misc/references.bib


execute: 
  warning: false
  freeze: true


format: 
  clean-revealjs:
    css: misc/style-slides.css
    code-line-numbers: false
    theme: beige
    footer: "[home](index.html)"