project:
  type: book
  output-dir: _book
  
book:
  title: "ADSL GIScience and Geodatabases"
  author: "Nils Ratnaweera"
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com
  chapters:
    - index.qmd
    - part: Vector Data Lecture
      chapters:
      - simple-features.qmd
      - vector-io.qmd
      - spatial-operations.qmd
    - vector-data-exercise.qmd
    - part: Raster Data Lecture
      chapters:
      - raster-data.qmd
      - raster-io.qmd
      - raster-operations.qmd
      - raster-vector-operations.qmd
    # - part: Raster Data Exercises
    #   chapters: 
    #   - raster-data-exercise.qmd


format: 
  html:
    number-depth: -1
    number-sections: false
    css: misc/style-book.css
    include-after-body: misc/script.html
